# server port config
server:
  port: 8000
  
# orale driver config
spring:
  servlet:
    multipart:
      file-size-threshold: 1MB
      max-file-size: 100MB
      max-request-size: 100MB   
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: dwine
    password: dwine   
  mail:
    host: smtp.gmail.com
    port: 587
    username: dwine.com
    password: www.dwine.com
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

# mybatis config
mybatis:
  mapper-locations: mappers/**/*.xml


