# server port config
server:  port: 8000
  
# orale driver config
spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: dwine
    password: dwine
    
# mybatis config
mybatis:  mapper-locations: mappers/**/*.xml
